no_metadata = true
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 32
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
dynamo_backend = "no"
enable_bucket = true
gradient_checkpointing = false
low_vram = false

###### huggingface ######
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""

max_bucket_reso = 256
max_data_loader_n_workers = 2
max_grad_norm = 1.0
max_token_length = 75
min_bucket_reso = 64
mixed_precision = "bf16"
no_half_vae = true
output_dir = "test_sdxl_sd3_auto"
output_name = "last"
pretrained_model_name_or_path = ""
prior_loss_weight = 0.0
resolution = "128,128"
sample_prompts = ""
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "bf16"
train_data_dir = "img"
training_comment = "loss_optimized_pixel_smash_128px_fix"
xformers = true

###### steps and epochs ######
max_train_epochs = 150
save_every_n_epochs = 50

###### loss function ######
loss_type = "l2"

###### batch size ######
train_batch_size = 32
gradient_accumulation_steps = 1

###### optimizer ######
optimizer_type = "AdamW8bit"
optimizer_args = [ "weight_decay=0.0", "betas=(0.9, 0.999)" ]
unet_lr = 0.001
text_encoder_lr = 0.0001

###### lr scheduler ######
lr_scheduler = "cosine"
lr_warmup_steps = 0
min_lr_ratio = 0.001

###### adaptive tuning ######
auto_tune = false

###### noise offset ######
noise_offset_type = "Original"
noise_offset_dynamic = false

###### misc ######
network_dim = 128
network_alpha = 128
network_module = "networks.lora"
network_args = [ "conv_dim=128", "conv_alpha=128" ]
network_dropout = 0.0
caption_dropout_rate = 0.0
clip_skip = 2
max_timestep = 1000
min_snr_gamma = 100
scale_weight_norms = 0
seed = 2951032222
